#!/usr/bin/env node

const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { spawnSync } = require("node:child_process");

const SOURCE_OBJECT = "mushmom-stats/stats/jsonl/2026-07.jsonl";
const DESTINATION_OBJECT = "mushmom-stats/stats/json/2026-07.json";
const MONTH = "2026-07";

function parseJsonl(text) {
  const trimmed = text.trim();
  if (trimmed === "") throw new Error("Source JSONL contains no rows.");

  let previous = -1;
  return trimmed.split(/\r?\n/).map((line, index) => {
    let row;
    try {
      row = JSON.parse(line);
    } catch {
      throw new Error(`Invalid source JSONL at line ${index + 1}: malformed JSON.`);
    }
    if (!isStatsRow(row)) {
      throw new Error(`Invalid source JSONL at line ${index + 1}: expected a compact stats tuple.`);
    }
    if (monthForTimestamp(row[0]) !== MONTH) {
      throw new Error(`Invalid source JSONL at line ${index + 1}: timestamp is outside ${MONTH}.`);
    }
    if (row[0] < previous) {
      throw new Error(`Invalid source JSONL at line ${index + 1}: timestamps must be ascending.`);
    }
    previous = row[0];
    return row;
  });
}

function serializeRowJson(rows) {
  if (!Array.isArray(rows) || rows.length === 0 || !rows.every(isStatsRow)) {
    throw new Error("Cannot serialize invalid or empty stats rows.");
  }
  return `[${rows.map((row) => JSON.stringify(row)).join(",")}]`;
}

function isStatsRow(row) {
  if (!Array.isArray(row) || (row.length !== 2 && row.length !== 3)
    || !isNonnegativeInteger(row[0])) return false;
  if (row[1] === null) {
    return row.length === 3 && isNonnegativeInteger(row[2]) && row[2] > 0;
  }
  return isNonnegativeInteger(row[1])
    && (row.length === 2 || isNonnegativeInteger(row[2]));
}

function isNonnegativeInteger(value) {
  return Number.isSafeInteger(value) && value >= 0;
}

function monthForTimestamp(timestamp) {
  const date = new Date(timestamp * 1000);
  return Number.isNaN(date.getTime()) ? null : date.toISOString().slice(0, 7);
}

function runWrangler(args, options = {}) {
  const executable = process.platform === "win32" ? "npx.cmd" : "npx";
  return spawnSync(executable, ["wrangler", ...args], {
    cwd: path.resolve(__dirname, ".."),
    encoding: "utf8",
    stdio: options.capture ? "pipe" : "inherit",
  });
}

function requireSuccessful(result, action) {
  if (result.error) throw result.error;
  if (result.status !== 0) {
    const detail = result.stderr?.trim() || result.stdout?.trim();
    throw new Error(`${action} failed${detail ? `: ${detail}` : "."}`);
  }
}

function parseArgs(args) {
  const allowed = new Set(["--apply", "--force"]);
  const flags = new Set();
  for (const arg of args) {
    if (!allowed.has(arg) || flags.has(arg)) {
      throw new Error("Usage: npm run migrate:stats-json [-- --apply [--force]]");
    }
    flags.add(arg);
  }
  if (flags.has("--force") && !flags.has("--apply")) {
    throw new Error("--force requires --apply.");
  }
  return { apply: flags.has("--apply"), force: flags.has("--force") };
}

function main(args = process.argv.slice(2)) {
  const { apply, force } = parseArgs(args);

  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "mushmom-stats-migration-"));
  const sourcePath = path.join(tempDir, "2026-07.jsonl");
  const destinationPath = path.join(tempDir, "2026-07.json");
  const verificationPath = path.join(tempDir, "verified.json");

  try {
    requireSuccessful(runWrangler([
      "r2", "object", "get", SOURCE_OBJECT, "--remote", "--file", sourcePath,
    ], { capture: true }), `Downloading ${SOURCE_OBJECT}`);

    const rows = parseJsonl(fs.readFileSync(sourcePath, "utf8"));
    const output = serializeRowJson(rows);
    fs.writeFileSync(destinationPath, output);
    console.log(`Validated ${rows.length} rows and generated ${Buffer.byteLength(output)} JSON bytes.`);

    if (!apply) {
      console.log("Dry run complete. Re-run with --apply to upload the JSON object.");
      return;
    }

    const existing = runWrangler([
      "r2", "object", "get", DESTINATION_OBJECT, "--remote", "--file", verificationPath,
    ], { capture: true });
    if (existing.status === 0) {
      if (fs.readFileSync(destinationPath).equals(fs.readFileSync(verificationPath))) {
        console.log(`Destination ${DESTINATION_OBJECT} already has the generated bytes; nothing to do.`);
        console.log(`Source preserved: ${SOURCE_OBJECT}`);
        return;
      }
      if (!force) {
        throw new Error(`Destination ${DESTINATION_OBJECT} differs; re-run with --apply --force to overwrite it.`);
      }
    }
    const lookupError = `${existing.stderr ?? ""}\n${existing.stdout ?? ""}`;
    if (!/(?:does not exist|not found|10007)/i.test(lookupError)) {
      requireSuccessful(existing, `Checking ${DESTINATION_OBJECT}`);
    }

    requireSuccessful(runWrangler([
      "r2", "object", "put", DESTINATION_OBJECT, "--remote",
      "--file", destinationPath, "--content-type", "application/json; charset=utf-8",
    ], { capture: true }), `Uploading ${DESTINATION_OBJECT}`);
    fs.rmSync(verificationPath, { force: true });
    requireSuccessful(runWrangler([
      "r2", "object", "get", DESTINATION_OBJECT, "--remote", "--file", verificationPath,
    ], { capture: true }), `Verifying ${DESTINATION_OBJECT}`);

    if (!fs.readFileSync(destinationPath).equals(fs.readFileSync(verificationPath))) {
      throw new Error("Uploaded JSON verification failed: R2 bytes differ from generated bytes.");
    }
    console.log(`Migration complete: ${DESTINATION_OBJECT}`);
    console.log(`Source preserved: ${SOURCE_OBJECT}`);
  } finally {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }
}

if (require.main === module) {
  try {
    main();
  } catch (error) {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  }
}

module.exports = { MONTH, SOURCE_OBJECT, DESTINATION_OBJECT, parseArgs, parseJsonl, serializeRowJson };
